export const MEDALS = [
  {
    normalLargeIcon: 'newarrival_large',
    normalMediumIcon: 'newarrival_medium',
    disabledLargeIcon: 'newarrival_medium_disabled',
    disabledMediumIcon: 'newarrival_medium_disabled',
    group: 'NEW_ARRIVAL',
    title: 'New Arrival',
    description: 'Winning a new customer',
    repeat: 'MONTHLY',
    isGolden: true,
    id: 0
  },
  {
    normalLargeIcon: 'thecollector_large_1of6',
    normalMediumIcon: 'thecollector_medium_1of6',
    disabledLargeIcon: 'thecollector_medium_disabled',
    disabledMediumIcon: 'thecollector_medium_disabled',
    group: 'THE_COLLECTOR',
    title: 'The Collector(1)',
    description: 'Have 1 customers',
    repeat: 'QUARTERLY',
    isGolden: false,
    id: 1
  },
  {
    normalLargeIcon: 'thecollector_large_2of6',
    normalMediumIcon: 'thecollector_medium_2of6',
    disabledLargeIcon: 'thecollector_medium_disabled',
    disabledMediumIcon: 'thecollector_medium_disabled',
    group: 'THE_COLLECTOR',
    title: 'The Collector(2)',
    description: 'Have 2 customers',
    repeat: 'QUARTERLY',
    isGolden: false,
    id: 2
  },
  {
    normalLargeIcon: 'thecollector_large_3of6',
    normalMediumIcon: 'thecollector_medium_3of6',
    disabledLargeIcon: 'thecollector_medium_disabled',
    disabledMediumIcon: 'thecollector_medium_disabled',
    group: 'THE_COLLECTOR',
    title: 'The Collector(3)',
    description: 'Have 3 customers',
    repeat: 'QUARTERLY',
    isGolden: false,
    id: 3
  },
  {
    normalLargeIcon: 'thecollector_large_4of6',
    normalMediumIcon: 'thecollector_medium_4of6',
    disabledLargeIcon: 'thecollector_medium_disabled',
    disabledMediumIcon: 'thecollector_medium_disabled',
    group: 'THE_COLLECTOR',
    title: 'The Collector(4)',
    description: 'Have 4 customers',
    repeat: 'QUARTERLY',
    isGolden: false,
    id: 4
  },
  {
    normalLargeIcon: 'thecollector_large_5of6',
    normalMediumIcon: 'thecollector_medium_5of6',
    disabledLargeIcon: 'thecollector_medium_disabled',
    disabledMediumIcon: 'thecollector_medium_disabled',
    group: 'THE_COLLECTOR',
    title: 'The Collector(5)',
    description: 'Have 5 customers',
    repeat: 'QUARTERLY',
    isGolden: false,
    id: 5
  },
  {
    normalLargeIcon: 'thecollector_large_6of6',
    normalMediumIcon: 'thecollector_medium_6of6',
    disabledLargeIcon: 'thecollector_medium_disabled',
    disabledMediumIcon: 'thecollector_medium_disabled',
    group: 'THE_COLLECTOR',
    title: 'The Collector',
    description: 'Have More than 5 customers',
    repeat: 'QUARTERLY',
    isGolden: true,
    id: 6
  },
  {
    normalLargeIcon: 'thearcher_large',
    normalMediumIcon: 'thearcher_medium',
    disabledLargeIcon: 'thearcher_medium_disabled',
    disabledMediumIcon: 'thearcher_medium_disabled',
    group: 'THE_ARCHER',
    title: 'The Archer',
    description: 'Signed 3 products with the same customer',
    repeat: 'QUARTERLY',
    isGolden: true,
    id: 7
  },
  {
    normalLargeIcon: 'exceptional_large',
    normalMediumIcon: 'exceptional_medium',
    disabledLargeIcon: 'exceptional_medium_disabled',
    disabledMediumIcon: 'exceptional_medium_disabled',
    group: 'EXCEPTIONAL',
    title: 'Exceptional',
    description: 'Personalized description',
    repeat: 'ONGOING',
    isGolden: true,
    id: 8
  },
  {
    normalLargeIcon: 'thegatherer_large_1of6',
    normalMediumIcon: 'thegatherer_medium_1of6',
    disabledLargeIcon: 'thegatherer_medium_disabled',
    disabledMediumIcon: 'thegatherer_medium_disabled',
    group: 'THE_GATHERER',
    title: 'The Gatherer(1)',
    description: 'Have 1 deal',
    repeat: 'MONTHLY',
    isGolden: false,
    id: 9
  },
  {
    normalLargeIcon: 'thegatherer_large_2of6',
    normalMediumIcon: 'thegatherer_medium_2of6',
    disabledLargeIcon: 'thegatherer_medium_disabled',
    disabledMediumIcon: 'thegatherer_medium_disabled',
    group: 'THE_GATHERER',
    title: 'The Gatherer(2)',
    description: 'Have 2 deals',
    repeat: 'MONTHLY',
    isGolden: false,
    id: 10
  },
  {
    normalLargeIcon: 'thegatherer_large_3of6',
    normalMediumIcon: 'thegatherer_medium_3of6',
    disabledLargeIcon: 'thegatherer_medium_disabled',
    disabledMediumIcon: 'thegatherer_medium_disabled',
    group: 'THE_GATHERER',
    title: 'The Gatherer(3)',
    description: 'Have 3 deals',
    repeat: 'MONTHLY',
    isGolden: false,
    id: 11
  },
  {
    normalLargeIcon: 'thegatherer_large_4of6',
    normalMediumIcon: 'thegatherer_medium_4of6',
    disabledLargeIcon: 'thegatherer_medium_disabled',
    disabledMediumIcon: 'thegatherer_medium_disabled',
    group: 'THE_GATHERER',
    title: 'The Gatherer(4)',
    description: 'Have 4 deals',
    repeat: 'MONTHLY',
    isGolden: false,
    id: 12
  },
  {
    normalLargeIcon: 'thegatherer_large_5of6',
    normalMediumIcon: 'thegatherer_medium_5of6',
    disabledLargeIcon: 'thegatherer_medium_disabled',
    disabledMediumIcon: 'thegatherer_medium_disabled',
    group: 'THE_GATHERER',
    title: 'The Gatherer(5)',
    description: 'Have 5 deals',
    repeat: 'MONTHLY',
    isGolden: false,
    id: 13
  },
  {
    normalLargeIcon: 'thegatherer_large_6of6',
    normalMediumIcon: 'thegatherer_medium_6of6',
    disabledLargeIcon: 'thegatherer_medium_disabled',
    disabledMediumIcon: 'thegatherer_medium_disabled',
    group: 'THE_GATHERER',
    title: 'The Gatherer',
    description: 'More than 5 deals',
    repeat: 'MONTHLY',
    isGolden: true,
    id: 14
  },
  {
    normalLargeIcon: 'thetall_large_1',
    normalMediumIcon: 'thetall_medium_1',
    disabledLargeIcon: 'thetall_medium_disabled',
    disabledMediumIcon: 'thetall_medium_disabled',
    group: 'THE_TALLS',
    title: 'The Talls',
    description: 'Highest number of deals in team',
    repeat: 'QUARTERLY',
    isGolden: true,
    id: 15
  },
  {
    normalLargeIcon: 'thetall_large_2',
    normalMediumIcon: 'thetall_medium_2',
    disabledLargeIcon: 'thetall_medium_disabled',
    disabledMediumIcon: 'thetall_medium_disabled',
    group: 'THE_TALLS',
    title: 'The Talls(2nd)',
    description: 'Second Highest number of deals in team',
    repeat: 'QUARTERLY',
    isGolden: false,
    id: 16
  },
  {
    normalLargeIcon: 'thetall_large_3',
    normalMediumIcon: 'thetall_medium_3',
    disabledLargeIcon: 'thetall_medium_disabled',
    disabledMediumIcon: 'thetall_medium_disabled',
    group: 'THE_TALLS',
    title: 'The Talls(3rd)',
    description: 'Third Highest number of deals in team',
    repeat: 'QUARTERLY',
    isGolden: false,
    id: 17
  },
  {
    normalLargeIcon: 'thechief_large',
    normalMediumIcon: 'thechief_medium',
    disabledLargeIcon: 'thechief_medium_disabled',
    disabledMediumIcon: 'thechief_medium_disabled',
    group: 'THE_CHIEF',
    title: 'The Chief',
    description: 'Highest sales deal in team/region',
    repeat: 'MONTHLY',
    isGolden: true,
    id: 18
  },
  {
    normalLargeIcon: 'theslow_large',
    normalMediumIcon: 'theslow_medium',
    disabledLargeIcon: 'theslow_medium_disabled',
    disabledMediumIcon: 'theslow_medium_disabled',
    group: 'THE_SLOW_TH',
    title: 'The Slow.th',
    description: 'Slow quarter, you have not completed any sale',
    repeat: 'QUARTERLY',
    isGolden: true,
    id: 29
  },
  {
    normalLargeIcon: 'getmemymoney_large',
    normalMediumIcon: 'getmemymoney_medium',
    disabledLargeIcon: 'getmemymoney_medium_disabled',
    disabledMediumIcon: 'getmemymoney_medium_disabled',
    group: 'RUN_OR_ELSE',
    title: 'Run, or else...',
    description: 'You have more than xyz% of collections not fulfilled',
    repeat: 'ONGOING',
    isGolden: true,
    id: 20
  },
  {
    normalLargeIcon: 'hotstuff_large',
    normalMediumIcon: 'hotstuff_medium',
    disabledLargeIcon: 'hotstuff_medium_disabled',
    disabledMediumIcon: 'hotstuff_medium_disabled',
    group: 'HOT_STUFF',
    title: 'Hot Stuff',
    description: 'Highest transaction volume in the team',
    repeat: 'MONTHLY',
    isGolden: true,
    id: 21
  }
];

export const MEDALS_DICT = {};
MEDALS.forEach(item => {
  MEDALS_DICT[item.id] = item;
});
